const products = [
  {
    id: 1,
    name: "Air Zoom Pegasus",
    price: 1412,
    category: "sports",
    image: "assets/images/shoe2.jpg",
    seller: "Nike",

    purchases: 0,
    rating: 0,
    reviews: 0,
    stock: 10,
  },
  {
    id: 2,
    name: "Nike Revolution 6",
    price: 1231,
    category: "men",
    image: "assets/images/shoe3.jpg",
    seller: "Nike",

    purchases: 0,
    rating: 0,
    reviews: 0,
    stock: 120,
  },
  {
    id: 3,
    name: "Nike Ultraboost",
    price: 4121,
    category: "women",
    image: "assets/images/shoe1.jpg",
    seller: "Nike",

    purchases: 35,
    rating: 4.8,
    reviews: 87,
    stock: 32,
  },
  {
    id: 4,
    name: "New Balance 327 V1 Women's Sneaker Shoes",
    price: 1999,
    category: "women",
    image: "assets/images/shoe4.jpg",
    seller: "New Balance",

    purchases: 30,
    rating: 4,
    reviews: 17,
    stock: 13,
  },
  {
    id: 5,
    name: "Nike Run Defy Women's Road Running Shoes",
    price: 2342,
    category: "women",
    image: "assets/images/shoe5.jpg",
    seller: "Nike",

    purchases: 0,
    rating: 0,
    reviews: 0,
    stock: 10,
  },
  {
    id: 6,
    name: "Lacoste Women's Carnaby Set white",
    price: 3425,
    category: "women",
    image: "assets/images/shoe6.jpg",
    seller: "MangBen",

    purchases: 2,
    rating: 4,
    reviews: 27,
    stock: 10,
  },
  {
    id: 7,
    name: "On Women's Cloud 6",
    price: 5345,
    category: "women",
    image: "assets/images/shoe7.jpg",
    seller: "Nike",

    purchases: 0,
    rating: 0,
    reviews: 0,
    stock: 10,
  },
  {
    id: 8,
    name: "Nike Zoom Fly 6 Men's Road Racing Shoes",
    price: 1400,
    category: "men",
    image: "assets/images/shoe8.jpg",
    seller: "Nike",

    purchases: 0,
    rating: 0,
    reviews: 0,
    stock: 10,
  },
  {
    id: 9,
    name: "ALDO Dinbrenn Oxford Shoes",
    price: 1200,
    category: "men",
    image: "assets/images/shoe9.jpg",
    seller: "MangBen",

    purchases: 0,
    rating: 0,
    reviews: 0,
    stock: 10,
  },
  {
    id: 10,
    name: "Nike Air Force 1 '07 Men's",
    price: 1533,
    category: "men",
    image: "assets/images/shoe10.jpg",
    seller: "MangBen",

    purchases: 0,
    rating: 0,
    reviews: 0,
    stock: 10,
  },
  
];
